[tool.poetry]
name = "ddcci-plasmoid-backend"
version = "0.1.1"
description = "Backend for ddcci-plasmoid"
authors = ["David Himmelstoß <77309510+davidhi7@users.noreply.github.com>"]
license = "MIT"
packages = [{include = "ddcci_plasmoid_backend"}]

[tool.poetry.dependencies]
python = "^3.10"
fasteners = "^0.18"
pytest = "^7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
python_files = "Node_test.py"
python_classes = "*Test"
python_functions = "test_*"
addopts = "--pyargs ddcci_plasmoid_backend"
